'use strict';
const $=id=>document.getElementById(id);
const screens=['intro','mapScreen','game','result'];
let state,timer,toastTimer;
function show(id){screens.forEach(s=>$(s).classList.toggle('hidden',s!==id));document.querySelectorAll('.steps span').forEach((e,i)=>e.classList.toggle('active',i===screens.indexOf(id)));}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),3500);}
const groups=[{name:'일산',color:'#7F77DD',ids:[0],x:105,y:75},{name:'상암·성북',color:'#1D9E75',ids:[1,2],x:345,y:120},{name:'서울 도심',color:'#E24B4A',ids:[3,4,5,6,7],x:425,y:230},{name:'마곡·여의도',color:'#378ADD',ids:[8,9,10,11],x:185,y:270},{name:'구로·관악',color:'#639922',ids:[12,13,14],x:270,y:430},{name:'강남·서초',color:'#D85A30',ids:Array.from({length:13},(_,i)=>i+15),x:575,y:375},{name:'분당',color:'#D4537E',ids:[28,29,30],x:670,y:550},{name:'하남',color:'#BA7517',ids:[31],x:805,y:220}];
function atlas(){let svg='<svg viewBox="0 0 920 660" role="img" aria-label="서울 경기 32매장의 지역별 관광 도식 지도"><path d="M50 80 Q180 5 280 60 T510 50 L720 90 840 165 875 310 775 420 800 590 630 620 540 530 350 570 200 490 140 350 45 300Z" fill="#fffaec" stroke="#dbd5bb" stroke-dasharray="6 5"/><path d="M15 220 Q160 180 230 310 T435 330 T650 270 T920 340" fill="none" stroke="#b3dcff" stroke-width="33"/><path d="M15 220 Q160 180 230 310 T435 330 T650 270 T920 340" fill="none" stroke="white" stroke-dasharray="5 8" stroke-width="2"/><text x="365" y="340" fill="#0567bd" font-size="15">한 강</text><text x="700" y="65" fill="#a4997f" font-size="22" letter-spacing="8">경기도</text><text x="355" y="190" fill="#c8bda4" font-size="28" letter-spacing="10">서울</text><text x="60" y="570" fill="#886d60" font-size="13">N ↑</text><text x="60" y="602" fill="#886d60" font-size="11">SEOUL & GYEONGGI COFFEE ATLAS</text>';
 groups.forEach((g,i)=>{if(i){const prev=groups[i-1];svg+=`<path d="M${prev.x} ${prev.y} Q${prev.x} ${g.y} ${g.x} ${g.y}" fill="none" stroke="${g.color}" stroke-width="3" stroke-dasharray="5 4"/>`;}svg+=`<circle cx="${g.x}" cy="${g.y}" r="29" fill="white" stroke="${g.color}" stroke-width="3"/><text x="${g.x}" y="${g.y+7}" text-anchor="middle" font-size="23">☕</text><rect x="${g.x-60}" y="${g.y+37}" width="120" height="26" rx="13" fill="white"/><text x="${g.x}" y="${g.y+55}" text-anchor="middle" fill="${g.color}" font-size="13" font-weight="bold">${g.name} · ${g.ids.length}개</text>`;g.ids.forEach((id,j)=>{const angle=(j/Math.max(g.ids.length,3))*Math.PI*2;const x=g.x+Math.cos(angle)*48,y=g.y+Math.sin(angle)*31;svg+=`<circle cx="${x}" cy="${y}" r="6" fill="${g.color}"><title>${storeNumbers[id]}. ${STORES[id]}</title></circle>`;});});$('atlas').innerHTML=svg+'</svg>';$('legend').innerHTML=groups.map(g=>`<span><i style="background:${g.color}"></i>${g.name}</span>`).join('');$('stores').innerHTML=numberedStoreIds.map(id=>`<span>${String(storeNumbers[id]).padStart(2,'0')} ${STORES[id]}</span>`).join('');}
// Outer rectangle, circular hub and four diagonal approaches share one movement graph.
let track=[];
for(let i=0;i<14;i++)track.push({x:590,y:760-i*46});
for(let i=0;i<6;i++)track.push({x:590-i*60,y:116});
for(let i=0;i<14;i++)track.push({x:230,y:116+i*46});
for(let i=0;i<6;i++)track.push({x:230+i*60,y:760});

for(let i=0;i<10;i++){const a=(-90+i*36)*Math.PI/180;track.push({x:410+125*Math.cos(a),y:438+125*Math.sin(a)});}
const arms=[];
[[0,44],[14,42],[20,48],[34,46]].forEach(([corner,ring])=>{const nodes=[];for(let i=1;i<=3;i++){nodes.push(track.length);track.push({x:track[corner].x+(track[ring].x-track[corner].x)*i/4,y:track[corner].y+(track[ring].y-track[corner].y)*i/4});}arms.push({corner,ring,nodes});});
let shopSlots=[20,24,9,12,15,16,14,13,27,28,22,23,34,36,38,40,50,42,59,61,44,53,54,56,57,46,48,51,1,5,3,7];
// Keep only the start and actual stores; each edge now advances one visible stop.
const retained=[0,...shopSlots].sort((a,b)=>a-b);
const remap=new Map(retained.map((old,index)=>[old,index]));
track=retained.map(old=>({...track[old],zone:old<40?'outer':old<50?'ring':'diagonal',side:old<14?'right':old<20?'top':old<34?'left':'bottom',ringTop:old===40}));
const outerCount=track.filter(p=>p.zone==='outer').length;
const ringStart=outerCount;
const ringCount=track.filter(p=>p.zone==='ring').length;
shopSlots=shopSlots.map(old=>remap.get(old));
arms.forEach(a=>{a.corner=remap.get(a.corner);a.ring=remap.get(a.ring);a.nodes=a.nodes.filter(n=>remap.has(n)).map(n=>remap.get(n));});
// Display numbering follows the outer perimeter, each diagonal arm, then the hub.
const numberedSlots=[...Array.from({length:outerCount-1},(_,i)=>i+1),...arms.flatMap(a=>a.nodes),...Array.from({length:ringCount},(_,i)=>ringStart+i)];
const numberedStoreIds=numberedSlots.map(slot=>shopSlots.indexOf(slot));
const storeNumbers=STORES.map((_,id)=>numberedStoreIds.indexOf(id)+1);
function branchAt(pos){return arms.find(a=>a.corner===pos||a.ring===pos);}
function moveOne(first){const a=branchAt(state.position);if(first&&state.route==='diagonal'&&a){state.travel=state.position===a.corner?'in':'out';state.position=state.travel==='in'?a.nodes[0]:a.nodes[a.nodes.length-1];return;}if(state.position<outerCount){state.position=(state.position+1)%outerCount;return;}if(state.position<ringStart+ringCount){state.position=ringStart+(state.position-ringStart+1)%ringCount;return;}const arm=arms.find(a=>a.nodes.includes(state.position));const i=arm.nodes.indexOf(state.position);state.position=state.travel==='out'?(i===0?arm.corner:arm.nodes[i-1]):(i===arm.nodes.length-1?arm.ring:arm.nodes[i+1]);}
function randomInt(max){const a=new Uint32Array(1);let n,limit=Math.floor(4294967296/max)*max;do{crypto.getRandomValues(a);n=a[0];}while(n>=limit);return n%max;}
function fresh(){const ids=Array.from({length:32},(_,i)=>i);for(let i=31;i>0;i--){const j=randomInt(i+1);[ids[i],ids[j]]=[ids[j],ids[i]];}return{position:0,turns:4,visited:new Set(),bonus:new Set(ids.slice(0,6)),point:new Set(ids.slice(6,14)),claimed:new Set(),points:0,phase:'ready',route:'outer',travel:'in',log:[],shared:false,coupon:false,missions:0,pendingPoint:null,pendingCorner:false};}
function board(){let s='<svg viewBox="0 0 820 850" role="img" aria-label="매장명이 표시된 직사각형, 대각선과 중앙 순환선 윷놀이판"><path d="M590 760V116H230V760Z" fill="none" stroke="#8c5b42" stroke-width="3"/><circle cx="410" cy="438" r="125" fill="#ecf6ff" fill-opacity=".55" stroke="#0567bd" stroke-width="2" stroke-dasharray="6 5"/><text x="410" y="69" text-anchor="middle" fill="#c20d16" font-size="22" font-style="italic" font-family="Georgia">Tim Hortons Coffee Journey</text>';
arms.forEach(a=>{s+='<path d="M'+track[a.corner].x+' '+track[a.corner].y+'L'+track[a.ring].x+' '+track[a.ring].y+'" stroke="#c20d16" stroke-width="2" stroke-dasharray="6 5"/>';});
track.forEach((p,i)=>{const id=shopSlots.indexOf(i),visited=state.visited.has(id),corner=arms.some(a=>a.corner===i);s+='<circle cx="'+p.x+'" cy="'+p.y+'" r="'+(corner?19:id>=0?12:4)+'" fill="'+(visited?'#19a966':id>=0?(p.zone==='ring'?'#0567bd':'#c20d16'):'#b0b3ba')+'" stroke="#fffaec" stroke-width="2"/>';if(i===0)s+='<text x="'+p.x+'" y="'+(p.y+4)+'" text-anchor="middle" fill="white" font-size="10">출발</text>';if(id>=0){s+='<text x="'+p.x+'" y="'+(p.y+4)+'" text-anchor="middle" fill="white" font-size="10">'+storeNumbers[id]+'</text>';let x=p.x,y=p.y+5,anchor='middle';if(p.zone==='outer'&&p.side==='right'){x+=25;anchor='start';}else if(p.zone==='outer'&&p.side==='top'){y-=25;}else if(p.zone==='outer'&&p.side==='left'){x-=25;anchor='end';}else if(p.zone==='outer'&&p.side==='bottom'){y+=29;}else if(p.zone==='ring'){if(p.ringTop){y-=23;}else{x+=p.x>410?21:-21;anchor=p.x>410?'start':'end';}}else{const arm=arms.find(a=>a.nodes.includes(i));x+=track[arm.corner].x>410?-20:20;anchor=track[arm.corner].x>410?'end':'start';y-=9;}
const marker=state.bonus.has(id)?' ↻':state.point.has(id)?' Ⓟ':'';s+='<text x="'+x+'" y="'+y+'" text-anchor="'+anchor+'" fill="#392821" font-size="12" font-weight="600" paint-order="stroke" stroke="#fffaec" stroke-width="4" stroke-linejoin="round">'+STORES[id]+marker+'</text>';}});
const p=track[state.position];s+='<circle cx="'+p.x+'" cy="'+p.y+'" r="23" fill="none" stroke="#1190ff" stroke-width="3"/><text x="'+p.x+'" y="'+(p.y-27)+'" text-anchor="middle" font-size="23">☕</text><text x="620" y="793" fill="#886d60" font-size="13">출발 · 위로 이동 ↑</text></svg>';$('board').innerHTML=s;$('turns').textContent=state.turns;$('visits').textContent=state.visited.size;$('points').textContent=state.points+' P';$('history').textContent=state.log.slice().reverse().join(' / ');
}
function start(){clearInterval(timer);['routeDialog','pointDialog','continueDialog','missionDialog'].forEach(id=>$(id).close());state=fresh();show('game');$('sticks').classList.remove('air','casting','landed');$('throwBtn').disabled=false;$('throwBtn').textContent='윷 띄우기';$('roundLabel').textContent='던질 준비가 되었나요?';$('countdown').textContent='버튼을 누르면 5초 카운트다운!';$('timebar').style.width='100%';$('notice').textContent='출발! 정확히 도착한 매장에 도장을 찍어요.';board();}
function arm(){state.phase='air';$('sticks').classList.remove('casting','landed');state.deadline=performance.now()+5000;$('sticks').classList.add('air');$('throwBtn').textContent='던지기!';$('roundLabel').textContent='지금! 5초 안에 던져주세요';$('countdown').textContent='5.0초';timer=setInterval(()=>{const ms=Math.max(0,state.deadline-performance.now());$('countdown').textContent=(ms/1000).toFixed(1)+'초';$('timebar').style.width=(ms/50)+'%';if(!ms)timeout();},40);}
function timeout(){if(state.phase!=='air')return;clearInterval(timer);state.turns--;state.phase='ready';$('sticks').classList.remove('air');$('notice').textContent='시간 초과! 던지기 기회 1회를 사용했어요.';state.log.push('시간 초과');after();}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function roll(){if(state.phase!=='air')return;if(performance.now()>=state.deadline){timeout();return;}clearInterval(timer);state.phase='moving';state.turns--;$('throwBtn').disabled=true;$('sticks').classList.remove('air');$('sticks').classList.add('casting');const bits=Array.from({length:4},()=>randomInt(2));const sum=bits.reduce((a,b)=>a+b,0),steps=sum===0?5:sum;const name=['','도','개','걸','윷','모'][steps];document.querySelectorAll('.stick').forEach((e,i)=>e.textContent=bits[i]?'×':'');$('countdown').textContent=`${name}! ${steps}칸 이동`;$('notice').textContent='윷이 떨어지면 이동해요!';await sleep(950);$('sticks').classList.remove('casting');$('sticks').classList.add('landed');$('notice').textContent='다음 커피 정류장으로 이동 중…';for(let i=0;i<steps;i++){await sleep(180);moveOne(i===0);board();}const id=shopSlots.indexOf(state.position);let message=`${name} · ${steps}칸 이동. `;if(id>=0){const repeated=state.visited.has(id);state.visited.add(id);message+=`${STORES[id]} ${repeated?'다시 도착!':'방문 성공!'} `;if(!state.claimed.has(id)){state.claimed.add(id);if(state.bonus.has(id)){state.turns++;message+='행운의 추가 던지기 +1회!';}if(state.point.has(id)){const p=1+randomInt(3);state.points+=p;state.pendingPoint={amount:p,store:STORES[id]};message+=`시연 포인트 +${p}P!`;}}}else message+='출발점에 돌아왔어요! 출발점은 방문 매장에 포함되지 않아요.';$('notice').textContent=message;state.log.push(message);state.phase='ready';after(true);}
function cornerDirection(){const p=track[state.position],next=track[(state.position+1)%outerCount];if(next.x<p.x)return '← 왼쪽으로';if(next.x>p.x)return '오른쪽으로 →';return next.y>p.y?'아래로 ↓':'위로 ↑';}
function openRoute(){state.phase='choosing';$('routeLocation').textContent=state.position===0?'출발점에 도착했어요.':STORES[shopSlots.indexOf(state.position)]+'에 도착했어요.';$('outerChoice').textContent=cornerDirection();$('routeDialog').showModal();}
function chooseRoute(route){if(state.phase!=='choosing')return;state.route=route;state.pendingCorner=false;state.phase='ready';$('routeDialog').close();$('notice').textContent=route==='diagonal'?'대각선으로 출발해요. 다음 윷을 띄워주세요!':cornerDirection()+' 이동해요. 다음 윷을 띄워주세요!';$('throwBtn').focus();}
const missions=[{title:'오늘 마시고 싶은 커피는?',options:['따뜻한 커피 ☕','시원한 커피 🧊']},{title:'누구와 커피 여행을 떠날까요?',options:['나만의 여유 시간','친구와 함께']},{title:'커피 한 잔이 생각나는 순간은?',options:['하루를 시작할 때','오후에 잠깐 쉴 때']}];
function after(landed=false){if(landed){state.route=state.position>=ringStart&&state.position<ringStart+ringCount&&branchAt(state.position)?'diagonal':'outer';state.pendingCorner=arms.some(a=>a.corner===state.position);}state.phase=state.turns?'ready':'done';board();$('throwBtn').disabled=false;$('throwBtn').textContent=state.turns>0?'다음 윷 띄우기':'여행 결과 보기';if(state.pendingPoint){state.phase='point';$('pointAmount').textContent=state.pendingPoint.amount+'P 적립!';$('pointStore').textContent=state.pendingPoint.store;$('pointDialog').showModal();return;}continueFlow();}
function continueFlow(){if(!state.turns){state.phase='exhausted';const available=state.missions<missions.length;$('continueText').textContent=available?'커피 취향을 하나 고르면, 지금 위치에서 2번 더 던질 수 있어요. 이어서 하시겠어요?':'준비된 미션도 모두 마쳤어요. 이번 여행의 방문 매장과 쿠폰을 확인해보세요.';$('continueYes').classList.toggle('hidden',!available);$('continueNo').textContent=available?'그만하기':'결과 보기';$('missionCount').textContent=available?'추가 기회 미션 '+(state.missions+1)+' / '+missions.length:'오늘의 여행 수고했어요!';$('continueDialog').showModal();return;}state.phase='ready';if(state.pendingCorner)openRoute();}
function closePoint(){if(state.phase!=='point')return;state.pendingPoint=null;$('pointDialog').close();continueFlow();}
function openMission(){if(state.phase!=='exhausted'||state.missions>=missions.length)return;state.phase='mission';$('continueDialog').close();const m=missions[state.missions];$('missionTitle').textContent=m.title;$('missionA').textContent=m.options[0];$('missionB').textContent=m.options[1];$('missionDialog').showModal();}
function completeMission(choice){if(state.phase!=='mission'||state.missions>=missions.length||![0,1].includes(choice))return;state.missions++;state.turns=2;$('missionDialog').close();$('notice').textContent='취향 선택 완료! 지금 위치에서 2번 더 여행해요.';state.log.push('취향 미션 '+state.missions+' 완료 · +2회');state.phase='ready';after();if(state.phase==='ready')$('throwBtn').focus();}
function stopContinue(){if(!['exhausted','mission'].includes(state.phase))return;$('continueDialog').close();$('missionDialog').close();state.phase='done';finish();}
function finish(){show('result');$('finalVisits').textContent=state.visited.size;$('visitedNames').textContent=state.visited.size?[...state.visited].map(i=>STORES[i]).join(' · '):'이번에는 잠시 스쳐 간 여행. 다음 여행에서 매장을 만나보세요!';$('pointSummary').textContent=`이번 여행에서 모은 시연 포인트 ${state.points}P`;$('couponBtn').disabled=false;$('couponBtn').textContent='쿠폰 받기 · 시연';$('shareBtn').disabled=false;$('shareBtn').textContent='공유하면 5P · 시연';}
$('outerChoice').onclick=()=>chooseRoute('outer');$('diagonalChoice').onclick=()=>chooseRoute('diagonal');$('routeDialog').addEventListener('cancel',e=>{e.preventDefault();chooseRoute('outer');});$('pointClose').onclick=closePoint;$('pointDialog').addEventListener('cancel',e=>{e.preventDefault();closePoint();});$('continueYes').onclick=openMission;$('continueNo').onclick=stopContinue;$('missionA').onclick=()=>completeMission(0);$('missionB').onclick=()=>completeMission(1);$('missionCancel').onclick=stopContinue;['continueDialog','missionDialog'].forEach(id=>$(id).addEventListener('cancel',e=>{e.preventDefault();stopContinue();}));
$('mapBtn').onclick=()=>show('mapScreen');$('backBtn').onclick=()=>show('intro');$('startBtn').onclick=start;$('replayBtn').onclick=()=>show('mapScreen');$('throwBtn').onclick=()=>{if(state.phase==='ready')arm();else if(state.phase==='air')roll();else if(state.phase==='done')finish();};$('couponBtn').onclick=()=>{state.coupon=true;$('couponBtn').disabled=true;$('couponBtn').textContent='시연 쿠폰 받기 완료';toast('제안용 쿠폰입니다. 실제 발급은 운영 연동 후 가능합니다.');};$('shareBtn').onclick=()=>{if(state.shared)return;state.shared=true;$('shareBtn').disabled=true;$('shareBtn').textContent='공유 보상 미리보기 +5P';$('pointSummary').textContent=`시연 포인트 ${state.points}P + 공유 보상 예시 5P`;toast('공유·5P 보상 화면의 시연입니다. 실제 공유와 적립은 진행되지 않습니다.');};atlas();show('intro');

