const fs=require('fs'),d='games/timhortons-tour/';let s=fs.readFileSync(d+'app.js','utf8');s=s.replace('let state,timer,toastTimer;','let state,timer,toastTimer,adTimer;');s=s.replace("coupon:false};","coupon:false,adUsed:false,pendingCorner:false};");const b=s.indexOf('const junction=branchAt(state.position);'),e=s.indexOf('function start()',b);s=s.slice(0,b)+'}\n'+s.slice(e);s=s.replace("function start(){clearInterval(timer);","function start(){clearInterval(timer);clearInterval(adTimer);$('routeDialog').close();$('adDialog').close();$('adExtraBtn').classList.add('hidden');");s=s.replace("$('routeBtn').disabled=true;",'');s=s.replace("state.phase='ready';after();}\nfunction after", "state.phase='ready';after(true);}\nfunction after");const a=s.indexOf('function after('),z=s.indexOf('function finish()',a);s=s.slice(0,a)+`function cornerDirection(){const p=track[state.position],next=track[(state.position+1)%outerCount];if(next.x<p.x)return '← 왼쪽으로';if(next.x>p.x)return '오른쪽으로 →';return next.y>p.y?'아래로 ↓':'위로 ↑';}
function openRoute(){state.phase='choosing';$('routeLocation').textContent=state.position===0?'출발점에 도착했어요.':STORES[shopSlots.indexOf(state.position)]+'에 도착했어요.';$('outerChoice').textContent=cornerDirection();$('routeDialog').showModal();}
function chooseRoute(route){if(state.phase!=='choosing')return;state.route=route;state.pendingCorner=false;state.phase='ready';$('routeDialog').close();$('notice').textContent=route==='diagonal'?'대각선으로 출발해요. 다음 윷을 띄워주세요!':cornerDirection()+' 이동해요. 다음 윷을 띄워주세요!';$('throwBtn').focus();}
function after(landed=false){if(landed){state.route=state.position>=ringStart&&state.position<ringStart+ringCount&&branchAt(state.position)?'diagonal':'outer';state.pendingCorner=arms.some(a=>a.corner===state.position);}state.phase=state.turns?'ready':'done';board();$('throwBtn').disabled=false;$('throwBtn').textContent=state.turns>0?'다음 윷 띄우기':'여행 결과 보기';$('adExtraBtn').classList.toggle('hidden',state.turns>0||state.adUsed);if(state.turns>0&&state.pendingCorner)openRoute();}
function openAd(){if(state.phase!=='done'||state.adUsed)return;state.phase='ad';state.adDeadline=performance.now()+5000;$('adComplete').disabled=true;$('adComplete').textContent='5초 후 2번 더 받기';$('adDialog').showModal();adTimer=setInterval(()=>{const remaining=Math.max(0,Math.ceil((state.adDeadline-performance.now())/1000));$('adComplete').textContent=remaining?remaining+'초 후 2번 더 받기':'시연 완료 · 2번 더 받기';$('adComplete').disabled=remaining>0;if(!remaining)clearInterval(adTimer);},100);}
function cancelAd(){if(state.phase!=='ad')return;clearInterval(adTimer);state.phase='done';$('adDialog').close();$('adExtraBtn').focus();}
function completeAd(){if(state.phase!=='ad'||state.adUsed||performance.now()<state.adDeadline)return;clearInterval(adTimer);state.adUsed=true;state.turns=2;state.phase='ready';$('adDialog').close();$('notice').textContent='시연 광고 완료! 지금 위치에서 2번 더 떠나보세요.';state.log.push('광고 시연 · 추가 던지기 +2회');after();$('throwBtn').focus();}
`+s.slice(z);const r=s.indexOf("$('routeBtn').onclick="),n=s.indexOf("$('mapBtn').onclick",r);s=s.slice(0,r)+`$('outerChoice').onclick=()=>chooseRoute('outer');$('diagonalChoice').onclick=()=>chooseRoute('diagonal');$('routeDialog').addEventListener('cancel',e=>{e.preventDefault();chooseRoute('outer');});$('adExtraBtn').onclick=openAd;$('adCancel').onclick=cancelAd;$('adComplete').onclick=completeAd;$('adDialog').addEventListener('cancel',e=>{e.preventDefault();cancelAd();});
`+s.slice(n);fs.writeFileSync(d+'app.js',s);
let h=fs.readFileSync(d+'index.html','utf8');h=h.replace('<button class="secondary hidden" id="routeBtn" style="width:100%;margin-bottom:8px"></button>','');h=h.replace('<div class="notice" id="notice"','<button class="secondary hidden" id="adExtraBtn" style="width:100%;margin-top:8px">팀홀튼 광고 보고 2번 더 · 시연</button><div class="notice" id="notice"');h=h.replace('꼭짓점과 가운데 원의 연결점에서는 경로 버튼으로 대각선을 선택할 수 있어요. 선택한 경로는 다음 던지기에 적용됩니다.','모서리에 딱 멈추면 팝업에서 다음 방향을 골라요. 가운데 원의 연결 매장에 멈추면 다음 던지기는 바깥으로 나가는 대각선으로 이동해요.');h=h.replace('추가 던지기는 보너스 매장에서만 지급됩니다.','보너스 매장은 +1회, 기회 소진 후 광고 시연은 게임당 한 번 +2회를 제공합니다.');h=h.replace('<script src="stores.js">',`<dialog id="routeDialog" aria-labelledby="routeTitle"><span class="eyebrow">CHOOSE YOUR WAY</span><h2 id="routeTitle">어디로 갈까요?</h2><p id="routeLocation" class="muted"></p><p>다음 윷을 던지기 전에<br>여행할 방향을 골라주세요.</p><div class="actions"><button class="secondary" id="outerChoice">왼쪽으로 ←</button><button class="primary" id="diagonalChoice">대각선으로 ↗</button></div></dialog>
<dialog id="adDialog" aria-labelledby="adTitle"><span class="pill">광고 시연 · 실제 광고 아님</span><h2 id="adTitle">한 잔의 여유,<br>두 번의 새로운 기회.</h2><div class="ad-cup">☕</div><span class="logo">Tim Hortons</span><p>지금 위치에서 여행을 이어가세요.<br>방문 기록과 모은 포인트는 그대로!</p><p class="muted">5초짜리 제안용 광고 화면입니다.</p><div class="actions"><button class="primary" id="adComplete" disabled>5초 후 2번 더 받기</button></div><button class="ad-cancel" id="adCancel">그만 보고 돌아가기</button></dialog>
<script src="stores.js">`);h=h.replace('</style>',`dialog{border:1px solid #e8ded0;border-radius:24px;padding:32px;max-width:420px;width:calc(100% - 40px);background:#fffaec;color:#392821;text-align:center;box-shadow:0 20px 80px #39282133}dialog::backdrop{background:#39282199;backdrop-filter:blur(3px)}dialog .actions{flex-wrap:wrap}dialog button{min-width:120px}.ad-cup{font-size:70px;margin:20px}.ad-cancel{background:transparent;color:#886d60;padding:16px;margin-top:8px;text-decoration:underline}
</style>`);fs.writeFileSync(d+'index.html',h);
