const fs=require('fs');const dir='games/timhortons-tour/';let h=fs.readFileSync(dir+'index.html','utf8');h=h.replace('<div class="board-stage">','<div class="board-viewport"><div class="board-stage">').replace('</div></div><div class="legend"><span>🍁 매장','</div></div></div><div class="legend"><span>🍁 매장');h=h.replace('</style>',`.game-layout{grid-template-columns:1fr}.board-stage{max-width:820px;margin:auto}.board-viewport{overflow-x:auto;border-radius:20px}.throw-panel{position:static;max-width:600px;margin:auto}.board-stage .sticks{top:51.5%}.board-hint{font-size:12px;color:#886d60}@media(max-width:650px){.board-stage{width:680px;min-width:680px}.board-stage .sticks{width:170px;gap:12px}.board-stage .stick{height:94px;width:23px;font-size:22px}}
</style>`);h=h.replace('<div class="board-viewport">','<p class="board-hint">매장에 딱 멈추면 방문 성공! 작은 화면에서는 판을 좌우로 밀어 확인하세요.</p><div class="board-viewport">');fs.writeFileSync(dir+'index.html',h);
let t=fs.readFileSync(dir+'test.cjs','utf8');const a=t.indexOf('(async()=>{await');t=t.slice(0,a)+`(async()=>{await vm.runInContext(\`(async()=>{
if(STORES.length!==32||new Set(shopSlots).size!==32||track.length!==62)throw Error('inventory');
start();if(state.turns!==4||state.bonus.size!==6||state.point.size!==8)throw Error('initial state');
state.position=1;randomInt=()=>1;state.bonus=new Set([shopSlots.indexOf(5)]);state.point.clear();arm();await roll();if(state.position!==5||state.visited.size!==1||state.turns!==4)throw Error('bonus landing');
state.position=1;arm();await roll();if(state.visited.size!==1||state.turns!==3)throw Error('repeat bonus');
start();state.route='diagonal';randomInt=()=>1;arm();await roll();if(state.position!==44||state.visited.size!==1)throw Error('diagonal into ring');
state.route='diagonal';arm();await roll();if(state.position!==0)throw Error('diagonal out');
start();state.position=48;randomInt=()=>0;arm();await roll();if(state.position!==43)throw Error('ring wrap');
start();state.position=37;randomInt=()=>0;arm();await roll();if(state.position!==2||state.visited.size!==0)throw Error('outer wrap excludes passed stores');
state.turns=1;arm();timeout();if(state.turns!==0||state.phase!=='done')throw Error('timeout');finish();
start();const seen=new Set([0]),pending=[0];while(pending.length){const pos=pending.pop();for(const route of ['outer','diagonal'])for(const travel of ['in','out']){state.position=pos;state.route=route;state.travel=travel;moveOne(true);if(!seen.has(state.position)){seen.add(state.position);pending.push(state.position);}}}if(shopSlots.some(p=>!seen.has(p)))throw Error('unreachable store');
if(!document.getElementById('board').innerHTML.includes(STORES[0]))throw Error('store names');
})()\`,ctx);console.log('PASS: 32 stores, exact visits, one-time bonus, inward/outward diagonal movement, both loops, timeout, all stores reachable, labels');})().catch(e=>{console.error(e);process.exitCode=1});\n`;fs.writeFileSync(dir+'test.cjs',t);
let r=fs.readFileSync(dir+'README.md','utf8').replace('48칸 순환 경로: 32개 매장과 16개 이동 칸.','62칸 연결 경로: 직사각형 외곽 40칸, 가운데 원 10칸, 대각선 12칸. 32개 매장을 외곽 19개·원 5개·대각선 8개로 배치.').replace('윷·모 자체 추가 턴 및 대각선 지름길은 적용하지 않은 제안 규칙.','윷·모 자체 추가 턴은 없음. 꼭짓점 또는 원의 연결점에 착지하면 다음 던지기 전에 경로 버튼으로 대각선 진입/이탈 선택. 기본값은 현재 외곽/원 순환선 유지. 대각선 이동 중 턴이 끝나면 다음 턴에도 같은 방향으로 진행.');r+='\n## 보드 모션\n윷은 별도의 배경 없이 판 위에서 CSS 3D 회전·상승·낙하·바운스 모션을 사용합니다. PNG 파일 없이 투명 배경 효과를 구현했습니다. 동작 줄이기 설정 시 모션을 생략합니다. 작은 화면에서는 매장명 가독성을 위해 판을 좌우 스크롤합니다.\n';fs.writeFileSync(dir+'README.md',r);
