const fs=require('fs'),d='games/timhortons-tour/';let s=fs.readFileSync(d+'app.js','utf8');s=s.replace('let state,timer,toastTimer,adTimer;','let state,timer,toastTimer;');s=s.replace('adUsed:false,pendingCorner:false','missions:0,pendingPoint:null,pendingCorner:false');s=s.replace("clearInterval(adTimer);$('routeDialog').close();$('adDialog').close();$('adExtraBtn').classList.add('hidden');","['routeDialog','pointDialog','continueDialog','missionDialog'].forEach(id=>$(id).close());");s=s.replace('state.points+=p;message+=','state.points+=p;state.pendingPoint={amount:p,store:STORES[id]};message+=');const a=s.indexOf('function after('),b=s.indexOf('function finish()',a);s=s.slice(0,a)+`const missions=[{title:'오늘 마시고 싶은 커피는?',options:['따뜻한 커피 ☕','시원한 커피 🧊']},{title:'누구와 커피 여행을 떠날까요?',options:['나만의 여유 시간','친구와 함께']},{title:'커피 한 잔이 생각나는 순간은?',options:['하루를 시작할 때','오후에 잠깐 쉴 때']}];
function after(landed=false){if(landed){state.route=state.position>=ringStart&&state.position<ringStart+ringCount&&branchAt(state.position)?'diagonal':'outer';state.pendingCorner=arms.some(a=>a.corner===state.position);}state.phase=state.turns?'ready':'done';board();$('throwBtn').disabled=false;$('throwBtn').textContent=state.turns>0?'다음 윷 띄우기':'여행 결과 보기';if(state.pendingPoint){state.phase='point';$('pointAmount').textContent=state.pendingPoint.amount+'P 적립!';$('pointStore').textContent=state.pendingPoint.store;$('pointDialog').showModal();return;}continueFlow();}
function continueFlow(){if(!state.turns){state.phase='exhausted';const available=state.missions<missions.length;$('continueText').textContent=available?'커피 취향을 하나 고르면, 지금 위치에서 2번 더 던질 수 있어요. 이어서 하시겠어요?':'준비된 미션도 모두 마쳤어요. 이번 여행의 방문 매장과 쿠폰을 확인해보세요.';$('continueYes').classList.toggle('hidden',!available);$('continueNo').textContent=available?'그만하기':'결과 보기';$('missionCount').textContent=available?'추가 기회 미션 '+(state.missions+1)+' / '+missions.length:'오늘의 여행 수고했어요!';$('continueDialog').showModal();return;}state.phase='ready';if(state.pendingCorner)openRoute();}
function closePoint(){if(state.phase!=='point')return;state.pendingPoint=null;$('pointDialog').close();continueFlow();}
function openMission(){if(state.phase!=='exhausted'||state.missions>=missions.length)return;state.phase='mission';$('continueDialog').close();const m=missions[state.missions];$('missionTitle').textContent=m.title;$('missionA').textContent=m.options[0];$('missionB').textContent=m.options[1];$('missionDialog').showModal();}
function completeMission(choice){if(state.phase!=='mission'||state.missions>=missions.length||![0,1].includes(choice))return;state.missions++;state.turns=2;$('missionDialog').close();$('notice').textContent='취향 선택 완료! 지금 위치에서 2번 더 여행해요.';state.log.push('취향 미션 '+state.missions+' 완료 · +2회');state.phase='ready';after();if(state.phase==='ready')$('throwBtn').focus();}
function stopContinue(){if(!['exhausted','mission'].includes(state.phase))return;$('continueDialog').close();$('missionDialog').close();state.phase='done';finish();}
`+s.slice(b);const x=s.indexOf("$('adExtraBtn').onclick"),y=s.indexOf("\n$('mapBtn')",x);s=s.slice(0,x)+`$('pointClose').onclick=closePoint;$('pointDialog').addEventListener('cancel',e=>{e.preventDefault();closePoint();});$('continueYes').onclick=openMission;$('continueNo').onclick=stopContinue;$('missionA').onclick=()=>completeMission(0);$('missionB').onclick=()=>completeMission(1);$('missionCancel').onclick=stopContinue;['continueDialog','missionDialog'].forEach(id=>$(id).addEventListener('cancel',e=>{e.preventDefault();stopContinue();}));`+s.slice(y);fs.writeFileSync(d+'app.js',s);
let h=fs.readFileSync(d+'index.html','utf8');h=h.replace('<button class="secondary hidden" id="adExtraBtn" style="width:100%;margin-top:8px">팀홀튼 광고 보고 2번 더 · 시연</button>','').replace('기회 소진 후 광고 시연은 게임당 한 번 +2회를 제공합니다.','기회 소진 후 취향 선택 미션은 회당 +2회, 최대 3번 제공됩니다.');const da=h.indexOf('<dialog id="adDialog"'),db=h.indexOf('</dialog>',da)+9;h=h.slice(0,da)+`<dialog id="pointDialog" aria-labelledby="pointAmount"><span class="pill">포인트 매장 도착</span><div style="font-size:60px;margin:20px">🪙</div><h2 id="pointAmount" style="font-size:42px;color:#c20d16">1P 적립!</h2><p id="pointStore"></p><p class="muted">제안용 시연 포인트입니다.<br>실제 포인트는 적립되지 않습니다.</p><button class="primary" id="pointClose">좋아요! 계속하기</button></dialog>
<dialog id="continueDialog" aria-labelledby="continueTitle"><span class="pill" id="missionCount"></span><h2 id="continueTitle">모든 기회가<br>소진됐습니다.</h2><p id="continueText"></p><div class="actions"><button class="secondary" id="continueNo">그만하기</button><button class="primary" id="continueYes">하기 · 2번 더</button></div><p class="muted">방문한 매장과 포인트는 그대로 유지됩니다.</p></dialog>
<dialog id="missionDialog" aria-labelledby="missionTitle"><span class="eyebrow">MY COFFEE MOMENT</span><h2 id="missionTitle"></h2><p>하나만 고르면 던지기 기회 +2회!</p><div class="actions"><button class="secondary" id="missionA"></button><button class="secondary" id="missionB"></button></div><p class="muted">정답은 없어요. 선택은 이번 시연에만 사용돼요.</p><button class="ad-cancel" id="missionCancel">그만하고 결과 보기</button></dialog>`+h.slice(db);fs.writeFileSync(d+'index.html',h);
